CREATE TABLE COMPANY (
    company_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    industry VARCHAR2(50),
    website_url VARCHAR2(200)

);

CREATE TABLE POSITION(
    position_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_name VARCHAR2(100) NOT NULL
);

CREATE TABLE EXPERIENCE (
    experience_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER ,--kullanıcı tablosu ile birleştirildiğinde güncellenecek
    company_id NUMBER REFERENCES COMPANY(company_id),
    position_id NUMBER REFERENCES POSITION(position_id),
    start_date DATE,
    end_date DATE,
    mulakat_sorulari VARCHAR2(4000)
);

CREATE TABLE REVIEW(
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumni_id NUMBER,--kullanıcı tablosu ile birleştirildiğinde güncellenecek
    company_id NUMBER REFERENCES COMPANY(company_id),
    content VARCHAR(4000),
    rating NUMBER(1) CHECK (rating BETWEEN 1 AND 5),
    is_anonymous CHAR(1) DEFAULT 'N',
    review_date DATE DEFAULT SYSDATE

);



-- Şirket ekleme
INSERT INTO COMPANY (name, industry, website_url) VALUES ('ASELSAN', 'Savunma Sanayi', 'aselsan.com.tr');
INSERT INTO COMPANY (name, industry, website_url) VALUES ('TUSAŞ', 'Havacılık', 'tusas.com');

-- Pozisyon ekleme
INSERT INTO POSITION (position_name) VALUES ('Gömülü Sistem Mühendisi');
INSERT INTO POSITION (position_name) VALUES ('Yazılım Stajyeri');
